openapi: 3.0.3
info:
  title: new-avocat API
  version: 0.1.0
paths:
  /auth/login:
    post:
      summary: Login (Sanctum session)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: OK
  /auth/register:
    post:
      summary: Register
      responses:
        '200':
          description: OK
  /auth/me:
    get:
      summary: Current user
      responses:
        '200':
          description: OK
  /auth/logout:
    post:
      summary: Logout
      responses:
        '200':
          description: OK

